version: '3'

services:
    db:
        image: postgres:13.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          ENCODING: UTF-8
          POSTGRES_BD: postgres
          PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
          - pgdata:/var/lib/postgresql/data/pgdata
        ports:
          - 15432:5432

volumes:
  pgdata:
